# Lista de palavras geradas pelo ImageAI em inglês
lista_original = ['person',  'bicycle',  'car', 'dog', 'motorcycle', 'truck', 
                  'handbag', 'traffic light', 'airplane', 'bus', 'train', 'boat',
                  'fire hydrant', 'stop_sign', 'parking meter', 'bench', 'bird', 'cat', 
                  'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 
                  'giraffe', 'backpack', 'umbrella', 'tie', 'suitcase', 'frisbee', 
                  'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 
                  'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 
                  'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 
                  'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 
                  'donot', 'cake', 'chair', 'couch', 'potted plant', 'bed', 
                  'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 
                  'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 
                  'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 
                  'hair dryer', 'toothbrush']

# Lista de palavras traduzidas do ImageAI para português                  
lista_traduzida = ['pessoa', 'bicicleta', 'carro', 'cachorro', 'motocicleta', 'caminhão', 
                   'bolsa de mão', 'semáforo', 'avião', 'ônibus', 'trem', 'barco', 
                   'hidrante', 'sinal de pare', 'parquímetro', 'banco', 'pássaro', 'gato', 
                   'cavalo', 'ovelha', 'vaca', 'elefante', 'urso', 'zebra', 
                   'girafa', 'mochila', 'guarda chuva', 'gravata', 'maleta', 'frisbee', 
                   'esquis', 'prancha de snowboard', 'bola de esportes', 'pipa', 'taco de baseball', 'luvas de baseball', 
                   'skate', 'pracha de surf', 'raquete de tênis', 'garrafa', 'taçade vinho', 'copo', 
                   'garfo', 'faca', 'colher', 'tigela', 'banana', 'maçã', 
                   'sanduíche', 'laranja', 'brócolis', 'cenoura', 'cachorro quente', 'pizza', 
                   'rosquinha', 'bolo', 'cadeira', 'sofá', 'vaso de planta', 'cama', 
                   'mesa de jantar', 'banheiro', 'televisor', 'computador portátil', 'mouse', 'controle remoto', 
                   'teclado', 'celular', 'microondas', 'forno', 'torradeira', 'pia', 
                   'refrigerador', 'livro', 'relógio', 'vaso', 'tesoura', 'ursinho de pelúcia', 
                   'seccador de cabelo', 'escova de dentes']